import type { SVGProps } from 'react';

export interface IconProps extends SVGProps<SVGSVGElement> {
  iconName: IconName;
}

export type IconName =
  | 'article'
  | 'articles'
  | 'burger-menu'
  | 'button-burguer'
  | 'button-burguer1'
  | 'close_simple'
  | 'close'
  | 'downloads'
  | 'eye'
  | 'facebook'
  | 'facebook1'
  | 'facelocation'
  | 'google'
  | 'home'
  | 'icon-upload-default'
  | 'icon-upload-primary'
  | 'left-arrow'
  | 'location'
  | 'logo'
  | 'magnifyingglass'
  | 'media'
  | 'pdf'
  | 'reference'
  | 'reference1'
  | 'right-arrow'
  | 'share'
  | 'start'
  | 'telegram'
  | 'vector'
  | 'volume'
  | 'volumes'
  | 'fi-rr-copy'
  | 'fi-sr-globe'
  | 'info'
  | 'Close-URL'
  | 'fi-rr-calendar'
  | 'fi-rr-clock-five'
  | 'whatsapp'
  | 'circle-quarters'
  | 'Close-URL';
