/**
 * @generated Automatically by the buildTokens function. Do not edit manually.
 * @see scripts/tokenizer.mjs
 */
export interface DesignTokens {
  breakpoints?: Record<string, string>;
  colors?: Record<string, string>;
  typography?: {
    fonts: Record<string, Record<string, string>>;
    fontSizes: Record<string, string>;
    fontWeights: Record<string, string | number>;
    lineHeights: Record<string, string | number>;
  };
  spacing?: Record<string, string>;
  shadows?: Record<string, string>;
}

const tokens: DesignTokens = {
  breakpoints: {
    small: '480px',
    small_mobile: '320px',
    small_mobile_large: '568px',
    medium: '768px',
    large: '1024px',
    large_tablet: '1112px',
    extra_large: '1280px',
  },
  colors: {
    border_radius_rounded: '8px',
    border_radius_circle: '50%',
    border: '#ccc',
    input_border_color: '#d1d5db',
    input_disabled_border_color: '#9da6cb',
    primary_main: '#7a44ff',
    secondary_main: '#9a4aff',
    tertiary_main: '#3994ff',
    success_main: '#23c965',
    danger_main: '#ff7066',
    warning_main: '#ffc14a',
    primary_twenty_five: '#f8f5ff',
    secondary_twenty_five: '#f5f5ff',
    tertiary_twenty_five: '#f5f9ff',
    success_twenty_five: '#f4fcf7',
    danger_twenty_five: '#fff8f7',
    warning_twenty_five: '#fffcf6',
    icontextstat_color_title: '#0e1223',
    icontextstat_color_text: '#667085',
    default_icon_dark: '#151a2d',
    text_main: '#02322c',
    text_secondary: '#6c757d',
    text_main_hover: '#000',
    background_main: '#f5f5f5',
    sky_error: "#0095cc",
    fill_primary: '#7a44ff',
    primary_soft: '#f8f5ff',
    main: '#fff',
    dark: '#151a2d',
    dark_soft: '#f0f1f3',
    disabled: '#bcc3e3',
    light: '#fff',
    negative: '#ff554a',
    negative_soft: '#fff8f7',
    positive: '#23c965',
    positive_soft: '#f4fcf7',
    primary: '#7a44ff',
    secondary: '#9a4aff',
    secondary_soft: '#faf6ff',
    tertiary: '#3994ff',
    tertiary_soft: '#f5f9ff',
    warning: '#f1c40f',
    warning_soft: '#fffcf6',
    gradient_lavender_bloom: 'linear-gradient(45deg, #6e4aff 0%, #ccbfff 100%)',
    gradient_coral_peach: 'linear-gradient(45deg, #f47cb4 0%, #fee2cc 100%)',
    gradient_serene_sky: 'linear-gradient(45deg, #8e9ff5 0%, #e3e8fd 100%)',
    gradient_ocean_turquoise: 'linear-gradient(45deg, #1b5de0 0%, #36ccc2 100%)',
    gradient_sunset_gold: 'linear-gradient(45deg, #ff880b 0%, #ffd8b0 100%)',
    gradient_orchid_twilight: 'linear-gradient(45deg, #c165dd 0%, #5c27fe 100%)',
    gradient_emerald_jade: 'linear-gradient(45deg, #2afeb7 0%, #08c792 100%)',
    gradient_sapphire_azure: 'linear-gradient(45deg, #658df5 0%, #1153fc 100%)',
    gradient_aqua_amethyst: 'linear-gradient(45deg, #1de5e2 0%, #b588f7 100%)',
    gradient_mint_lemonade: 'linear-gradient(45deg, #3fcab2 0%, #fbeb8e 100%)',
    gradient_fiery_lavender: 'linear-gradient(45deg, #fe3a0a 0%, #f0c8f4 100%)',
    gradient_violet_rose: 'linear-gradient(45deg, #9627fc 0%, #fbc4d2 100%)',
    gradient_pink_blossom: 'linear-gradient(45deg, #ff5886 0%, #ffb6fc 100%)',
    gradient_sky_magenta: 'linear-gradient(45deg, #8cd7f7 0%, #f674f9 100%)',
    gradient_neon_lime: 'linear-gradient(45deg, #a9ffdb 0%, #17d970 100%)',
    input_focus_color: '#7a44ff',
    input_error_color: '#ef4444',
    input_text_color: '#000',
    input_hint_color: '#6b7280',
    input_disabled_color: '#bcc3e3',
    input_disabled_opacity: '0.7',
    shadow_xs: '0 1px 2px rgba(0 0 0 / 5%)',
    shadow_sm: '0 1px 3px rgba(0 0 0 / 10%)',
    shadow_md: '0 4px 6px rgba(0 0 0 / 10%)',
    shadow_lg: '0 10px 15px rgba(0 0 0 / 10%)',
    shadow_xl: '0 20px 25px rgba(0 0 0 / 15%)',
    shadow_xxxl: '0 35px 60px rgba(0 0 0 / 20%)',
    size_xs: '1.5rem',
    size_sm: '2rem',
    size_md: '2.5rem',
    size_lg: '3rem',
    padding_large: '2rem',
    grid_item_padding: '20px',
    gridforge_container_size: '1200px',
    gridforge_gutter: '24px',
    state_disabled_opacity: '0.5',
    state_hover_opacity: '0.85',
    font_size_headingone: '3rem',
    font_size_headingtwo: '2.25rem',
    font_size_headingthree: '1.5',
    line_height_headingone: '4.5rem',
    line_height_headingtwo: '3.375rem',
    line_height_headingthree: '2.25rem',
    font_weight_regular: '400',
    font_weight_medium: '500',
    font_weight_semibold: '600',
    font_family_sans: "'Helvetica Neue', arial, sans-serif",
    font_family_serif: "'Georgia', serif",
    font_family_italic: "'Times New Roman', times, serif",
    font_family_monospace: "'Courier New', courier, monospace",
    icontextstat_weight_title: '500',
    icontextstat_weight_text: '300',
    icontextstat_fontsize_smalltitle: '1.125rem',
    icontextstat_fontsize_mediumtitle: '1.25rem',
    icontextstat_fontsize_largetitle: '1.5rem',
    icontextstat_fontsize_smalltext: '1rem',
    icontextstat_fontsize_mediumtext: '1.125rem',
    icontextstat_fontsize_largetext: '1.25rem',
    font_weight_bold: '700',
    font_size_primary: '1rem',
    font_size_first: '6rem',
    font_size_second: '1.75rem',
    font_size_third: '8rem',
    font_size_quarter: '2.5rem',
    font_size_fifth: '0.75rem',
    font_size_sixth: '0.938rem',
    font_weight_first: '400',
    font_weight_second: '800',
    font_weight_third: '600',
    line_height_default: '1.3',
    text_input: '#a6a6a6',
    quaternary_main: '#00526c',
    quintary_main: '#0793bf',
    size_main: '1.3rem',
    text_main_alpha: 'rgb(2 50 44 / 85%)',
    letter_spacing: '0.0625rem',
    font_weight: '700',
    background_desktop: 'rgb(217 217 217 / 40%)',
    background_color_black: 'rgb(0 0 0 / 30%)',
    display_xl: '4.5rem',
    display_lg: '3.5rem',
    display_xl_height: '4.375rem',
    display_lg_height: '3.75rem',
    display_regular_weight: '400',
    display_medium_weight: '500',
    display_color_light: '#fff',
    display_color_dark: '#0e1223',
    paragraph_xl: '24px',
    paragraph_lg: '20px',
    paragraph_md: '18px',
    paragraph_sm: '16px',
    paragraph_xs: '14px',
    paragraph_xl_height: '36px',
    paragraph_lg_height: '30px',
    paragraph_md_height: '27px',
    paragraph_sm_height: '24px',
    paragraph_xs_height: '21px',
    paragraph_color_dark: '#0e1223',
    paragraph_color_light: '#fff',
    stroke_dark: '#151a2d',
    stroke_dark_soft: '#e0e2e7',
    stroke_disabled: '#9da6cb',
    stroke_negative: '#ff554a',
    stroke_negative_soft: '#ffe2e0',
    stroke_positive: '#23c965',
    stroke_positive_soft: '#d3f4e0',
    stroke_primary: '#7a44ff',
    stroke_primary_soft: '#e4daff',
    stroke_secondary: '#9a4aff',
    stroke_secondary_soft: '#ebdbff',
    stroke_tertiary: '#3994ff',
    stroke_tertiary_soft: '#d7eaff',
    stroke_warning: '#ffc14a',
    stroke_warning_soft: '#fff3db',
    intenseviolet_main: '#7a44ff',
    violet_main: '#9a4aff',
    clear_main: '#9da6cb',
    green_main: '#23c965',
    error: '#ff5a5f',
    background_disabled: '#f5f5f5',
    focus: '#4b5fff',
    neutral_bg: '#f0f0f0',
    brand_bg: '#007bff',
    brand_icon: '#fff',
    disabled_icon: '#a0a0a0',
    input_error_border_color: '#ffe2e0',
    white: '#fff',
    black: '#000',
    danger: '#e74c3c',
    success: '#2ecc71',
    info: '#3498db',
    volume_title: '#00526C',
    volume_text: '#02322C',
    volume_date: '#000',
  },
  typography: {
    fonts: {
      Lato: {
        '300': '/fonts/Lato-Light.woff2',
        normal: '/fonts/Lato-Bold.woff2',
      },
      'Lato-bold': {
        bold: '/fonts/Lato-Bold.woff2',
      },
      Roboto: {
        normal: '/fonts/Roboto-Bold.woff2',
      },
      Montserrat: {
        '300': '/fonts/Montserrat-Light.woff2',
        normal: '/fonts/Montserrat-Italic.woff2',
      },
      'Poppins-Bolt': {
        normal: '/public/fonts/Poppins-Bold.ttf',
      },
      'Poppins-BoltItalic': {
        normal: '/public/fonts/Poppins-BoldItalic.ttf',
      },
      'Poppins-SemiBolt': {
        normal: '/public/fonts/Poppins-SemiBold.ttf',
      },
      'Poppins-SemiBoltItalic': {
        normal: '/public/fonts/Poppins-SemiBoldItalic.ttf',
      },
      'Poppins-Medium': {
        normal: '/public/fonts/Poppins-Medium.ttf',
      },
      'Poppins-MediumItalic': {
        normal: '/public/fonts/Poppins-MediumItalic.ttf',
      },
      'Poppins-Regular': {
        normal: '/public/fonts/Poppins-Regular.ttf',
      },
      'Poppins-RegularItalic': {
        normal: '/public/fonts/Poppins-Italic.ttf',
      },
      'Poppins-Light': {
        normal: '/public/fonts/Poppins-Light.ttf',
      },
      'Poppins-LightItalic': {
        normal: '/public/fonts/Poppins-LightItalic.ttf',
      },
    },
    fontSizes: {
      headingone: '3rem',
      headingtwo: '2.25rem',
      headingthree: '1.5',
      primary: '1rem',
      first: '6rem',
      second: '1.75rem',
      third: '8rem',
      quarter: '2.5rem',
      fifth: '0.75rem',
      sixth: '0.938rem',
    },
    fontWeights: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      first: '400',
      second: '800',
      third: '600',
      default: '700',
    },
    lineHeights: {
      headingone: '4.5rem',
      headingtwo: '3.375rem',
      headingthree: '2.25rem',
      default: '1.3',
    },
  },
  spacing: {
    padding_large: '2rem',
  },
};

export default tokens;
