module.exports = {
  rules: {
    'no-param-reassign': ['off', { props: false }],
    'no-mixed-operators': 0,
    'react/react-in-jsx-scope': 'off',
    'no-underscore-dangle': 0,
    'no-multiple-empty-lines': 0,
    'import/no-mutable-exports': 0,
    'import/extensions': 'off',
    'react/jsx-filename-extension': 'off',
    'import/no-unresolved': 'off',
    'no-console': 0,
    'max-len': 0,
    'linebreak-style': 0,
    'class-methods-use-this': 0,
    'missing-custom-element-compile-options': 0,
    'import/first': 0,
    'import/prefer-default-export': 0,
    'no-shadow': 'off',
    'lines-between-class-members': ['off', 'always', { exceptAfterSingleLine: true }],
    'no-useless-constructor': 'off',
    'react/require-default-props': ['off'],
    'react/jsx-key': [
      'warn',
      {
        checkFragmentShorthand: true,
      },
    ],
    'no-plusplus': ['off', { allowForLoopAfterthoughts: true }],
    'import/no-extraneous-dependencies': ['off'],
    'react/forbid-prop-types': ['off'],
    radix: ['off'],
    'react/prop-types': ['off'],
    'react/no-unused-prop-types': ['off'],
    'react/no-unknown-property': ['error'],
    'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    'func-names': ['off'],
    'react/jsx-wrap-multilines': ['error', { return: 'ignore' }],
    'no-unused-expressions': ['error', { allowShortCircuit: true }],
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-restricted-syntax': ['warn'],
    'jsx-a11y/no-static-element-interactions': ['warn'],
    'jsx-a11y/click-events-have-key-events': ['warn'],
    'jsx-a11y/interactive-supports-focus': ['warn'],
    'react/button-has-type': ['warn'],
    'no-nested-ternary': ['warn'],
    'react/no-array-index-key': ['warn'],
    'jsx-a11y/label-has-associated-control': ['warn'],
    'no-return-assign': ['warn'],
    '@typescript-eslint/no-namespace': 'off',
  },
};
