name: Deploy docker hub

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '>=18.19 <=18.21'
          cache: 'yarn'

      - name: Install specific Yarn version
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: List installed packages
        run: yarn list
      - name: Run lint
        run: yarn lint

      - name: Run lint:css
        run: yarn lint:css

      - name: Run test
        run: yarn test
      - name: Build Storybook
        if: github.ref == 'refs/heads/main'
        run: yarn build-storybook

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      - name: clean storybook folder
        if: github.ref == 'refs/heads/main'
        run: rm -rf ./storybook-static
      - name: Login in DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup envirronments variables
        run: | 
          echo "DOCKER_HUB_REPO=openscience" >> $GITHUB_ENV
          echo "DOCKER_USER_NAME=ditmar" >> $GITHUB_ENV
      - name: Get shour commit hash
        id: vars
        run: echo "GIT_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: build project
        run: yarn build
      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: docker build -t ditmar/${{ env.DOCKER_HUB_REPO }}:${{ env.GIT_COMMIT_HASH }} .
      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ditmar/${{ env.DOCKER_HUB_REPO }}:${{ env.GIT_COMMIT_HASH }} ditmar/${{ env.DOCKER_HUB_REPO }}:${{ env.GIT_COMMIT_HASH }}
          docker push ditmar/${{ env.DOCKER_HUB_REPO }}:${{ env.GIT_COMMIT_HASH }}
      - name: Remove local Docker image
        if: github.ref == 'refs/heads/main'
        run: docker rmi ditmar/${{ env.DOCKER_HUB_REPO }}:${{ env.GIT_COMMIT_HASH }}